// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: abstractaccount/v1/events.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventAccountRegistered is emitted when an AbstractAccount is registered.
type EventAccountRegistered struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	// CodeID is the implementation code active after registration.
	CodeID          uint64 `protobuf:"varint,2,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
	ContractAddr    string `protobuf:"bytes,3,opt,name=contract_addr,json=contractAddr,proto3" json:"contract_addr,omitempty"`
	AccountNumber   uint64 `protobuf:"varint,4,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	BootstrapCodeID uint64 `protobuf:"varint,5,opt,name=bootstrap_code_id,json=bootstrapCodeId,proto3" json:"bootstrap_code_id,omitempty"`
}

func (m *EventAccountRegistered) Reset()         { *m = EventAccountRegistered{} }
func (m *EventAccountRegistered) String() string { return proto.CompactTextString(m) }
func (*EventAccountRegistered) ProtoMessage()    {}
func (*EventAccountRegistered) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bd53b0900cad0fc, []int{0}
}
func (m *EventAccountRegistered) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventAccountRegistered) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventAccountRegistered.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventAccountRegistered) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventAccountRegistered.Merge(m, src)
}
func (m *EventAccountRegistered) XXX_Size() int {
	return m.Size()
}
func (m *EventAccountRegistered) XXX_DiscardUnknown() {
	xxx_messageInfo_EventAccountRegistered.DiscardUnknown(m)
}

var xxx_messageInfo_EventAccountRegistered proto.InternalMessageInfo

func (m *EventAccountRegistered) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *EventAccountRegistered) GetCodeID() uint64 {
	if m != nil {
		return m.CodeID
	}
	return 0
}

func (m *EventAccountRegistered) GetContractAddr() string {
	if m != nil {
		return m.ContractAddr
	}
	return ""
}

func (m *EventAccountRegistered) GetAccountNumber() uint64 {
	if m != nil {
		return m.AccountNumber
	}
	return 0
}

func (m *EventAccountRegistered) GetBootstrapCodeID() uint64 {
	if m != nil {
		return m.BootstrapCodeID
	}
	return 0
}

// EventAccountMigrated is emitted when an AbstractAccount is moved to the
// module-managed current implementation.
type EventAccountMigrated struct {
	ContractAddr string `protobuf:"bytes,1,opt,name=contract_addr,json=contractAddr,proto3" json:"contract_addr,omitempty"`
	CodeID       uint64 `protobuf:"varint,2,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
}

func (m *EventAccountMigrated) Reset()         { *m = EventAccountMigrated{} }
func (m *EventAccountMigrated) String() string { return proto.CompactTextString(m) }
func (*EventAccountMigrated) ProtoMessage()    {}
func (*EventAccountMigrated) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bd53b0900cad0fc, []int{1}
}
func (m *EventAccountMigrated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventAccountMigrated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventAccountMigrated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventAccountMigrated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventAccountMigrated.Merge(m, src)
}
func (m *EventAccountMigrated) XXX_Size() int {
	return m.Size()
}
func (m *EventAccountMigrated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventAccountMigrated.DiscardUnknown(m)
}

var xxx_messageInfo_EventAccountMigrated proto.InternalMessageInfo

func (m *EventAccountMigrated) GetContractAddr() string {
	if m != nil {
		return m.ContractAddr
	}
	return ""
}

func (m *EventAccountMigrated) GetCodeID() uint64 {
	if m != nil {
		return m.CodeID
	}
	return 0
}

func init() {
	proto.RegisterType((*EventAccountRegistered)(nil), "abstractaccount.v1.EventAccountRegistered")
	proto.RegisterType((*EventAccountMigrated)(nil), "abstractaccount.v1.EventAccountMigrated")
}

func init() { proto.RegisterFile("abstractaccount/v1/events.proto", fileDescriptor_6bd53b0900cad0fc) }

var fileDescriptor_6bd53b0900cad0fc = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0x4f, 0x4f, 0xfa, 0x40,
	0x14, 0x64, 0x7f, 0x3f, 0x84, 0xb8, 0x11, 0x89, 0x2b, 0x31, 0x8d, 0x87, 0x42, 0x20, 0x26, 0x5c,
	0xa0, 0x21, 0xde, 0x35, 0xa0, 0x1e, 0x38, 0xe8, 0xa1, 0x27, 0xe3, 0xa5, 0xee, 0xbf, 0xd4, 0x26,
	0xd2, 0x47, 0xb6, 0xaf, 0x44, 0xbf, 0x85, 0x1f, 0xcb, 0x23, 0x47, 0x4f, 0xc4, 0x14, 0x3f, 0x88,
	0x69, 0xe9, 0x26, 0x4a, 0x38, 0x78, 0xdb, 0x9d, 0x99, 0xf7, 0xde, 0x4c, 0x86, 0xb6, 0xb9, 0x48,
	0xd0, 0x70, 0x89, 0x5c, 0x4a, 0x48, 0x63, 0xf4, 0x16, 0x23, 0x4f, 0x2f, 0x74, 0x8c, 0xc9, 0x70,
	0x6e, 0x00, 0x81, 0xb1, 0x2d, 0xc1, 0x70, 0x31, 0x3a, 0x6d, 0x85, 0x10, 0x42, 0x41, 0x7b, 0xf9,
	0x6b, 0xa3, 0xec, 0x7e, 0x11, 0x7a, 0x72, 0x93, 0x8f, 0x8e, 0x37, 0x4a, 0x5f, 0x87, 0x51, 0x82,
	0xda, 0x68, 0xc5, 0x1c, 0x5a, 0x97, 0x46, 0x73, 0x04, 0xe3, 0x90, 0x0e, 0xe9, 0xef, 0xfb, 0xf6,
	0xcb, 0x7a, 0xb4, 0x2e, 0x41, 0xe9, 0x20, 0x52, 0xce, 0xbf, 0x0e, 0xe9, 0x57, 0x27, 0x34, 0x5b,
	0xb5, 0x6b, 0x57, 0xa0, 0xf4, 0xf4, 0xda, 0xaf, 0xe5, 0xd4, 0x54, 0xb1, 0x1e, 0x6d, 0x48, 0x88,
	0x0b, 0x17, 0x01, 0x57, 0xca, 0x38, 0xff, 0x8b, 0x25, 0x07, 0x16, 0x1c, 0x2b, 0x65, 0xd8, 0x19,
	0x3d, 0x2c, 0x2d, 0x06, 0x71, 0x3a, 0x13, 0xda, 0x38, 0xd5, 0x7c, 0xa1, 0xdf, 0x28, 0xd1, 0xbb,
	0x02, 0x64, 0x97, 0xf4, 0x48, 0x00, 0x60, 0x9e, 0x69, 0x1e, 0xd8, 0xd3, 0x7b, 0xc5, 0xe9, 0xe3,
	0x6c, 0xd5, 0x6e, 0x4e, 0x2c, 0x59, 0x7a, 0x68, 0x8a, 0x5f, 0x80, 0xea, 0x3e, 0xd2, 0xd6, 0xcf,
	0x94, 0xb7, 0x51, 0x68, 0x38, 0xea, 0x1d, 0x26, 0xc9, 0x0e, 0x93, 0x7f, 0x89, 0x3b, 0xb9, 0x7f,
	0xcf, 0x5c, 0xb2, 0xcc, 0x5c, 0xf2, 0x99, 0xb9, 0xe4, 0x6d, 0xed, 0x56, 0x96, 0x6b, 0xb7, 0xf2,
	0xb1, 0x76, 0x2b, 0x0f, 0x17, 0x61, 0x84, 0x4f, 0xa9, 0x18, 0x4a, 0x98, 0x79, 0x22, 0x35, 0x31,
	0x0e, 0x9e, 0xb9, 0x48, 0x3c, 0x5b, 0xd1, 0xc0, 0x96, 0xf8, 0xe2, 0x6d, 0xd7, 0x8a, 0xaf, 0x73,
	0x9d, 0x88, 0x5a, 0xd1, 0xd4, 0xf9, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x66, 0xd8, 0x48, 0x80,
	0xf6, 0x01, 0x00, 0x00,
}

func (m *EventAccountRegistered) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventAccountRegistered) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventAccountRegistered) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BootstrapCodeID != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.BootstrapCodeID))
		i--
		dAtA[i] = 0x28
	}
	if m.AccountNumber != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.AccountNumber))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ContractAddr) > 0 {
		i -= len(m.ContractAddr)
		copy(dAtA[i:], m.ContractAddr)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.ContractAddr)))
		i--
		dAtA[i] = 0x1a
	}
	if m.CodeID != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.CodeID))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventAccountMigrated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventAccountMigrated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventAccountMigrated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CodeID != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.CodeID))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ContractAddr) > 0 {
		i -= len(m.ContractAddr)
		copy(dAtA[i:], m.ContractAddr)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.ContractAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventAccountRegistered) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.CodeID != 0 {
		n += 1 + sovEvents(uint64(m.CodeID))
	}
	l = len(m.ContractAddr)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.AccountNumber != 0 {
		n += 1 + sovEvents(uint64(m.AccountNumber))
	}
	if m.BootstrapCodeID != 0 {
		n += 1 + sovEvents(uint64(m.BootstrapCodeID))
	}
	return n
}

func (m *EventAccountMigrated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddr)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.CodeID != 0 {
		n += 1 + sovEvents(uint64(m.CodeID))
	}
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventAccountRegistered) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventAccountRegistered: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventAccountRegistered: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodeID", wireType)
			}
			m.CodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CodeID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountNumber", wireType)
			}
			m.AccountNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AccountNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BootstrapCodeID", wireType)
			}
			m.BootstrapCodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BootstrapCodeID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventAccountMigrated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventAccountMigrated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventAccountMigrated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodeID", wireType)
			}
			m.CodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CodeID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
