// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: abstractaccount/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the abstractaccount module.
type Params struct {
	// AllowAllCodeIDs determines whether an AbstractAccount can be migrated with
	// a raw wasm MsgMigrateContract to any Wasm code ID:
	// - if set to true, any code ID can be used;
	// - if set to false, only code IDs whitelisted in the AllowedCodeIDs list can
	// be used.
	AllowAllCodeIDs bool `protobuf:"varint,1,opt,name=allow_all_code_ids,json=allowAllCodeIds,proto3" json:"allow_all_code_ids,omitempty"`
	// AllowedCodeIDs is the whitelist used for raw wasm migrations. Applications
	// should use MsgMigrateAccount instead, which selects ImplementationCodeID.
	AllowedCodeIDs []uint64 `protobuf:"varint,2,rep,packed,name=allowed_code_ids,json=allowedCodeIds,proto3" json:"allowed_code_ids,omitempty"`
	// MaxGasBefore is the maximum amount of gas that can be consumed by the
	// contract call in the before_tx decorator.
	//
	// Must be greater than zero.
	MaxGasBefore uint64 `protobuf:"varint,3,opt,name=max_gas_before,json=maxGasBefore,proto3" json:"max_gas_before,omitempty"`
	// MaxGasAfter is the maximum amount of gas that can be consumed by the
	// contract call in the after_tx decorator.
	//
	// Must be greater than zero.
	MaxGasAfter uint64 `protobuf:"varint,4,opt,name=max_gas_after,json=maxGasAfter,proto3" json:"max_gas_after,omitempty"`
	// BootstrapCodeID is the immutable Wasm code ID used by Instantiate2 so
	// account addresses remain stable across implementation upgrades. A zero
	// value disables account registration until governance configures it.
	BootstrapCodeID uint64 `protobuf:"varint,5,opt,name=bootstrap_code_id,json=bootstrapCodeId,proto3" json:"bootstrap_code_id,omitempty"`
	// ImplementationCodeID is the governance-controlled Wasm code ID new
	// accounts are migrated to immediately after deterministic instantiation.
	ImplementationCodeID uint64 `protobuf:"varint,6,opt,name=implementation_code_id,json=implementationCodeId,proto3" json:"implementation_code_id,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_9649df9baf604574, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetAllowAllCodeIDs() bool {
	if m != nil {
		return m.AllowAllCodeIDs
	}
	return false
}

func (m *Params) GetAllowedCodeIDs() []uint64 {
	if m != nil {
		return m.AllowedCodeIDs
	}
	return nil
}

func (m *Params) GetMaxGasBefore() uint64 {
	if m != nil {
		return m.MaxGasBefore
	}
	return 0
}

func (m *Params) GetMaxGasAfter() uint64 {
	if m != nil {
		return m.MaxGasAfter
	}
	return 0
}

func (m *Params) GetBootstrapCodeID() uint64 {
	if m != nil {
		return m.BootstrapCodeID
	}
	return 0
}

func (m *Params) GetImplementationCodeID() uint64 {
	if m != nil {
		return m.ImplementationCodeID
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "abstractaccount.v1.Params")
}

func init() { proto.RegisterFile("abstractaccount/v1/params.proto", fileDescriptor_9649df9baf604574) }

var fileDescriptor_9649df9baf604574 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x41, 0x4f, 0xfa, 0x30,
	0x18, 0xc6, 0x19, 0xf0, 0x27, 0xff, 0x54, 0x05, 0xad, 0xc4, 0x2c, 0x1e, 0x36, 0x42, 0x3c, 0x70,
	0x81, 0x85, 0x78, 0x35, 0xea, 0xa6, 0x89, 0xe1, 0x62, 0x0c, 0x27, 0xe3, 0x65, 0x79, 0xbb, 0x96,
	0xb9, 0xa4, 0x5b, 0x97, 0xb5, 0x20, 0x7e, 0x0b, 0x3f, 0x96, 0x47, 0x8e, 0x9e, 0x88, 0xd9, 0xbe,
	0x88, 0xd9, 0xe6, 0x14, 0xf0, 0xd6, 0x3e, 0xcf, 0xef, 0x7d, 0xf2, 0xb6, 0x0f, 0x32, 0x81, 0x48,
	0x95, 0x80, 0xa7, 0xc0, 0xf3, 0xc4, 0x3c, 0x52, 0xd6, 0x62, 0x6c, 0xc5, 0x90, 0x40, 0x28, 0x47,
	0x71, 0x22, 0x94, 0xc0, 0x78, 0x07, 0x18, 0x2d, 0xc6, 0xa7, 0x5d, 0x5f, 0xf8, 0xa2, 0xb0, 0xad,
	0xfc, 0x54, 0x92, 0xfd, 0xac, 0x8e, 0x5a, 0x0f, 0xc5, 0x28, 0xbe, 0x46, 0x18, 0x38, 0x17, 0x2f,
	0x2e, 0x70, 0xee, 0x7a, 0x82, 0x32, 0x37, 0xa0, 0x52, 0xd7, 0x7a, 0xda, 0xe0, 0xbf, 0x73, 0x9c,
	0xae, 0xcd, 0x8e, 0x9d, 0xbb, 0x36, 0xe7, 0x37, 0x82, 0xb2, 0xc9, 0xad, 0x9c, 0x76, 0x60, 0x53,
	0xa0, 0x12, 0x5f, 0xa0, 0xc3, 0x42, 0x62, 0xf4, 0x77, 0xbe, 0xde, 0x6b, 0x0c, 0x9a, 0x0e, 0x4e,
	0xd7, 0x66, 0xdb, 0x2e, 0xbd, 0x6a, 0xbc, 0x0d, 0x1b, 0x77, 0x2a, 0xf1, 0x19, 0x6a, 0x87, 0xb0,
	0x74, 0x7d, 0x90, 0x2e, 0x61, 0x33, 0x91, 0x30, 0xbd, 0xd1, 0xd3, 0x06, 0xcd, 0xe9, 0x7e, 0x08,
	0xcb, 0x3b, 0x90, 0x4e, 0xa1, 0xe1, 0x3e, 0x3a, 0xa8, 0x28, 0x98, 0x29, 0x96, 0xe8, 0xcd, 0x02,
	0xda, 0x2b, 0x21, 0x3b, 0x97, 0xf0, 0x15, 0x3a, 0x22, 0x42, 0xa8, 0xfc, 0x0b, 0xe2, 0x6a, 0x13,
	0xfd, 0x5f, 0xce, 0x95, 0x0f, 0x71, 0x2a, 0xb3, 0x5c, 0x65, 0xda, 0x21, 0x5b, 0x02, 0xc5, 0xf7,
	0xe8, 0x24, 0x08, 0x63, 0xce, 0x42, 0x16, 0x29, 0x50, 0x81, 0x88, 0x7e, 0x52, 0x5a, 0x45, 0x8a,
	0x9e, 0xae, 0xcd, 0xee, 0x64, 0x8b, 0xf8, 0x8e, 0xea, 0x06, 0x7f, 0x55, 0xea, 0x3c, 0xbe, 0xa7,
	0x86, 0xb6, 0x4a, 0x0d, 0xed, 0x33, 0x35, 0xb4, 0xb7, 0xcc, 0xa8, 0xad, 0x32, 0xa3, 0xf6, 0x91,
	0x19, 0xb5, 0xa7, 0x4b, 0x3f, 0x50, 0xcf, 0x73, 0x32, 0xf2, 0x44, 0x68, 0x91, 0x79, 0x12, 0xa9,
	0x21, 0x07, 0x22, 0xad, 0xaa, 0xbf, 0x61, 0xd5, 0xf0, 0xd2, 0xda, 0xed, 0x5c, 0xbd, 0xc6, 0x4c,
	0x92, 0x56, 0x51, 0xe3, 0xf9, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x82, 0xf0, 0xf1, 0xfd, 0x13,
	0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ImplementationCodeID != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ImplementationCodeID))
		i--
		dAtA[i] = 0x30
	}
	if m.BootstrapCodeID != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BootstrapCodeID))
		i--
		dAtA[i] = 0x28
	}
	if m.MaxGasAfter != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxGasAfter))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxGasBefore != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxGasBefore))
		i--
		dAtA[i] = 0x18
	}
	if len(m.AllowedCodeIDs) > 0 {
		dAtA2 := make([]byte, len(m.AllowedCodeIDs)*10)
		var j1 int
		for _, num := range m.AllowedCodeIDs {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintParams(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x12
	}
	if m.AllowAllCodeIDs {
		i--
		if m.AllowAllCodeIDs {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AllowAllCodeIDs {
		n += 2
	}
	if len(m.AllowedCodeIDs) > 0 {
		l = 0
		for _, e := range m.AllowedCodeIDs {
			l += sovParams(uint64(e))
		}
		n += 1 + sovParams(uint64(l)) + l
	}
	if m.MaxGasBefore != 0 {
		n += 1 + sovParams(uint64(m.MaxGasBefore))
	}
	if m.MaxGasAfter != 0 {
		n += 1 + sovParams(uint64(m.MaxGasAfter))
	}
	if m.BootstrapCodeID != 0 {
		n += 1 + sovParams(uint64(m.BootstrapCodeID))
	}
	if m.ImplementationCodeID != 0 {
		n += 1 + sovParams(uint64(m.ImplementationCodeID))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowAllCodeIDs", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AllowAllCodeIDs = bool(v != 0)
		case 2:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowParams
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.AllowedCodeIDs = append(m.AllowedCodeIDs, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowParams
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthParams
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthParams
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.AllowedCodeIDs) == 0 {
					m.AllowedCodeIDs = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowParams
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.AllowedCodeIDs = append(m.AllowedCodeIDs, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedCodeIDs", wireType)
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxGasBefore", wireType)
			}
			m.MaxGasBefore = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxGasBefore |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxGasAfter", wireType)
			}
			m.MaxGasAfter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxGasAfter |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BootstrapCodeID", wireType)
			}
			m.BootstrapCodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BootstrapCodeID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ImplementationCodeID", wireType)
			}
			m.ImplementationCodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ImplementationCodeID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
